// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverpush.proto

package com.zhicai.byteera.service.serversdk;

public final class ServerPush {
  private ServerPush() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhicaiproto.TestPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes data = 1;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code zhicaiproto.TestPayload}
   */
  public static final class TestPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zhicaiproto.TestPayload)
      TestPayloadOrBuilder {
    // Use TestPayload.newBuilder() to construct.
    private TestPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestPayload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestPayload defaultInstance;
    public static TestPayload getDefaultInstance() {
      return defaultInstance;
    }

    public TestPayload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_TestPayload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_TestPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicai.byteera.service.serversdk.ServerPush.TestPayload.class, com.zhicai.byteera.service.serversdk.ServerPush.TestPayload.Builder.class);
    }

    public static com.google.protobuf.Parser<TestPayload> PARSER =
        new com.google.protobuf.AbstractParser<TestPayload>() {
      public TestPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestPayload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestPayload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 1;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhicai.byteera.service.serversdk.ServerPush.TestPayload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhicaiproto.TestPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhicaiproto.TestPayload)
        com.zhicai.byteera.service.serversdk.ServerPush.TestPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_TestPayload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_TestPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicai.byteera.service.serversdk.ServerPush.TestPayload.class, com.zhicai.byteera.service.serversdk.ServerPush.TestPayload.Builder.class);
      }

      // Construct using com.zhicai.byteera.service.serversdk.ServerPush.TestPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_TestPayload_descriptor;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.TestPayload getDefaultInstanceForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.TestPayload.getDefaultInstance();
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.TestPayload build() {
        com.zhicai.byteera.service.serversdk.ServerPush.TestPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.TestPayload buildPartial() {
        com.zhicai.byteera.service.serversdk.ServerPush.TestPayload result = new com.zhicai.byteera.service.serversdk.ServerPush.TestPayload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicai.byteera.service.serversdk.ServerPush.TestPayload) {
          return mergeFrom((com.zhicai.byteera.service.serversdk.ServerPush.TestPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicai.byteera.service.serversdk.ServerPush.TestPayload other) {
        if (other == com.zhicai.byteera.service.serversdk.ServerPush.TestPayload.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicai.byteera.service.serversdk.ServerPush.TestPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicai.byteera.service.serversdk.ServerPush.TestPayload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 1;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:zhicaiproto.TestPayload)
    }

    static {
      defaultInstance = new TestPayload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:zhicaiproto.TestPayload)
  }

  public interface AddFriendRequestPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhicaiproto.AddFriendRequestPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string user_id = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>required string nickname = 2;</code>
     */
    boolean hasNickname();
    /**
     * <code>required string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>required string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>required string head_portrait = 3;</code>
     */
    boolean hasHeadPortrait();
    /**
     * <code>required string head_portrait = 3;</code>
     */
    java.lang.String getHeadPortrait();
    /**
     * <code>required string head_portrait = 3;</code>
     */
    com.google.protobuf.ByteString
        getHeadPortraitBytes();
  }
  /**
   * Protobuf type {@code zhicaiproto.AddFriendRequestPayload}
   */
  public static final class AddFriendRequestPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zhicaiproto.AddFriendRequestPayload)
      AddFriendRequestPayloadOrBuilder {
    // Use AddFriendRequestPayload.newBuilder() to construct.
    private AddFriendRequestPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFriendRequestPayload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFriendRequestPayload defaultInstance;
    public static AddFriendRequestPayload getDefaultInstance() {
      return defaultInstance;
    }

    public AddFriendRequestPayload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFriendRequestPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nickname_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              headPortrait_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_AddFriendRequestPayload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_AddFriendRequestPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload.class, com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFriendRequestPayload> PARSER =
        new com.google.protobuf.AbstractParser<AddFriendRequestPayload>() {
      public AddFriendRequestPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFriendRequestPayload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFriendRequestPayload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>required string user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user_id = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.Object nickname_;
    /**
     * <code>required string nickname = 2;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_PORTRAIT_FIELD_NUMBER = 3;
    private java.lang.Object headPortrait_;
    /**
     * <code>required string head_portrait = 3;</code>
     */
    public boolean hasHeadPortrait() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string head_portrait = 3;</code>
     */
    public java.lang.String getHeadPortrait() {
      java.lang.Object ref = headPortrait_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headPortrait_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string head_portrait = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHeadPortraitBytes() {
      java.lang.Object ref = headPortrait_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headPortrait_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = "";
      nickname_ = "";
      headPortrait_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeadPortrait()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNicknameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHeadPortraitBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNicknameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHeadPortraitBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhicaiproto.AddFriendRequestPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhicaiproto.AddFriendRequestPayload)
        com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_AddFriendRequestPayload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_AddFriendRequestPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload.class, com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload.Builder.class);
      }

      // Construct using com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        headPortrait_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_AddFriendRequestPayload_descriptor;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload getDefaultInstanceForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload.getDefaultInstance();
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload build() {
        com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload buildPartial() {
        com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload result = new com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickname_ = nickname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.headPortrait_ = headPortrait_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload) {
          return mergeFrom((com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload other) {
        if (other == com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000002;
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.hasHeadPortrait()) {
          bitField0_ |= 0x00000004;
          headPortrait_ = other.headPortrait_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasNickname()) {
          
          return false;
        }
        if (!hasHeadPortrait()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicai.byteera.service.serversdk.ServerPush.AddFriendRequestPayload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>required string user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>required string nickname = 2;</code>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nickname = 2;</code>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>required string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headPortrait_ = "";
      /**
       * <code>required string head_portrait = 3;</code>
       */
      public boolean hasHeadPortrait() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string head_portrait = 3;</code>
       */
      public java.lang.String getHeadPortrait() {
        java.lang.Object ref = headPortrait_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headPortrait_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string head_portrait = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHeadPortraitBytes() {
        java.lang.Object ref = headPortrait_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headPortrait_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string head_portrait = 3;</code>
       */
      public Builder setHeadPortrait(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        headPortrait_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string head_portrait = 3;</code>
       */
      public Builder clearHeadPortrait() {
        bitField0_ = (bitField0_ & ~0x00000004);
        headPortrait_ = getDefaultInstance().getHeadPortrait();
        onChanged();
        return this;
      }
      /**
       * <code>required string head_portrait = 3;</code>
       */
      public Builder setHeadPortraitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        headPortrait_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:zhicaiproto.AddFriendRequestPayload)
    }

    static {
      defaultInstance = new AddFriendRequestPayload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:zhicaiproto.AddFriendRequestPayload)
  }

  public interface PushMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhicaiproto.PushMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
     */
    com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type getType();

    /**
     * <code>required bytes payload = 2;</code>
     */
    boolean hasPayload();
    /**
     * <code>required bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code zhicaiproto.PushMsg}
   */
  public static final class PushMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zhicaiproto.PushMsg)
      PushMsgOrBuilder {
    // Use PushMsg.newBuilder() to construct.
    private PushMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PushMsg defaultInstance;
    public static PushMsg getDefaultInstance() {
      return defaultInstance;
    }

    public PushMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PushMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type value = com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_PushMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_PushMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.class, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<PushMsg> PARSER =
        new com.google.protobuf.AbstractParser<PushMsg>() {
      public PushMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code zhicaiproto.PushMsg.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Test = 1;</code>
       *
       * <pre>
       * payload 为 TestPayload
       * </pre>
       */
      Test(0, 1),
      /**
       * <code>AddFriend = 2;</code>
       *
       * <pre>
       * payload 为 AddFriendRequestPayload
       * </pre>
       */
      AddFriend(1, 2),
      ;

      /**
       * <code>Test = 1;</code>
       *
       * <pre>
       * payload 为 TestPayload
       * </pre>
       */
      public static final int Test_VALUE = 1;
      /**
       * <code>AddFriend = 2;</code>
       *
       * <pre>
       * payload 为 AddFriendRequestPayload
       * </pre>
       */
      public static final int AddFriend_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return Test;
          case 2: return AddFriend;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:zhicaiproto.PushMsg.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type type_;
    /**
     * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
     */
    public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type getType() {
      return type_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>required bytes payload = 2;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private void initFields() {
      type_ = com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type.Test;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhicai.byteera.service.serversdk.ServerPush.PushMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhicaiproto.PushMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhicaiproto.PushMsg)
        com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_PushMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_PushMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.class, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder.class);
      }

      // Construct using com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type.Test;
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_PushMsg_descriptor;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg getDefaultInstanceForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.getDefaultInstance();
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg build() {
        com.zhicai.byteera.service.serversdk.ServerPush.PushMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg buildPartial() {
        com.zhicai.byteera.service.serversdk.ServerPush.PushMsg result = new com.zhicai.byteera.service.serversdk.ServerPush.PushMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicai.byteera.service.serversdk.ServerPush.PushMsg) {
          return mergeFrom((com.zhicai.byteera.service.serversdk.ServerPush.PushMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicai.byteera.service.serversdk.ServerPush.PushMsg other) {
        if (other == com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicai.byteera.service.serversdk.ServerPush.PushMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicai.byteera.service.serversdk.ServerPush.PushMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type type_ = com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type.Test;
      /**
       * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
       */
      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type getType() {
        return type_;
      }
      /**
       * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
       */
      public Builder setType(com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .zhicaiproto.PushMsg.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Type.Test;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes payload = 2;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>required bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:zhicaiproto.PushMsg)
    }

    static {
      defaultInstance = new PushMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:zhicaiproto.PushMsg)
  }

  public interface ServerPushMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhicaiproto.ServerPushMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    java.util.List<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg> 
        getMsgList();
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    com.zhicai.byteera.service.serversdk.ServerPush.PushMsg getMsg(int index);
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    int getMsgCount();
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    java.util.List<? extends com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder> 
        getMsgOrBuilderList();
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder getMsgOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code zhicaiproto.ServerPushMsg}
   */
  public static final class ServerPushMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zhicaiproto.ServerPushMsg)
      ServerPushMsgOrBuilder {
    // Use ServerPushMsg.newBuilder() to construct.
    private ServerPushMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerPushMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerPushMsg defaultInstance;
    public static ServerPushMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ServerPushMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerPushMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                msg_ = new java.util.ArrayList<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg>();
                mutable_bitField0_ |= 0x00000001;
              }
              msg_.add(input.readMessage(com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = java.util.Collections.unmodifiableList(msg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_ServerPushMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_ServerPushMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg.class, com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerPushMsg> PARSER =
        new com.google.protobuf.AbstractParser<ServerPushMsg>() {
      public ServerPushMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerPushMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerPushMsg> getParserForType() {
      return PARSER;
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private java.util.List<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg> msg_;
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    public java.util.List<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg> getMsgList() {
      return msg_;
    }
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    public java.util.List<? extends com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder> 
        getMsgOrBuilderList() {
      return msg_;
    }
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    public int getMsgCount() {
      return msg_.size();
    }
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg getMsg(int index) {
      return msg_.get(index);
    }
    /**
     * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
     */
    public com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder getMsgOrBuilder(
        int index) {
      return msg_.get(index);
    }

    private void initFields() {
      msg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMsgCount(); i++) {
        if (!getMsg(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < msg_.size(); i++) {
        output.writeMessage(1, msg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < msg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhicaiproto.ServerPushMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhicaiproto.ServerPushMsg)
        com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_ServerPushMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_ServerPushMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg.class, com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg.Builder.class);
      }

      // Construct using com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          msgBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.internal_static_zhicaiproto_ServerPushMsg_descriptor;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg getDefaultInstanceForType() {
        return com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg.getDefaultInstance();
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg build() {
        com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg buildPartial() {
        com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg result = new com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg(this);
        int from_bitField0_ = bitField0_;
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            msg_ = java.util.Collections.unmodifiableList(msg_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg) {
          return mergeFrom((com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg other) {
        if (other == com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg.getDefaultInstance()) return this;
        if (msgBuilder_ == null) {
          if (!other.msg_.isEmpty()) {
            if (msg_.isEmpty()) {
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMsgIsMutable();
              msg_.addAll(other.msg_);
            }
            onChanged();
          }
        } else {
          if (!other.msg_.isEmpty()) {
            if (msgBuilder_.isEmpty()) {
              msgBuilder_.dispose();
              msgBuilder_ = null;
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000001);
              msgBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMsgFieldBuilder() : null;
            } else {
              msgBuilder_.addAllMessages(other.msg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMsgCount(); i++) {
          if (!getMsg(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicai.byteera.service.serversdk.ServerPush.ServerPushMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg> msg_ =
        java.util.Collections.emptyList();
      private void ensureMsgIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = new java.util.ArrayList<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg>(msg_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zhicai.byteera.service.serversdk.ServerPush.PushMsg, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder, com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder> msgBuilder_;

      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public java.util.List<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg> getMsgList() {
        if (msgBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msg_);
        } else {
          return msgBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public int getMsgCount() {
        if (msgBuilder_ == null) {
          return msg_.size();
        } else {
          return msgBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg getMsg(int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);
        } else {
          return msgBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder setMsg(
          int index, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.set(index, value);
          onChanged();
        } else {
          msgBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder setMsg(
          int index, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder addMsg(com.zhicai.byteera.service.serversdk.ServerPush.PushMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(value);
          onChanged();
        } else {
          msgBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder addMsg(
          int index, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(index, value);
          onChanged();
        } else {
          msgBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder addMsg(
          com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder addMsg(
          int index, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder addAllMsg(
          java.lang.Iterable<? extends com.zhicai.byteera.service.serversdk.ServerPush.PushMsg> values) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, msg_);
          onChanged();
        } else {
          msgBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          msgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public Builder removeMsg(int index) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.remove(index);
          onChanged();
        } else {
          msgBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder getMsgBuilder(
          int index) {
        return getMsgFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder getMsgOrBuilder(
          int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);  } else {
          return msgBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public java.util.List<? extends com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder> 
           getMsgOrBuilderList() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msg_);
        }
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder addMsgBuilder() {
        return getMsgFieldBuilder().addBuilder(
            com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder addMsgBuilder(
          int index) {
        return getMsgFieldBuilder().addBuilder(
            index, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .zhicaiproto.PushMsg msg = 1;</code>
       */
      public java.util.List<com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder> 
           getMsgBuilderList() {
        return getMsgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zhicai.byteera.service.serversdk.ServerPush.PushMsg, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder, com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zhicai.byteera.service.serversdk.ServerPush.PushMsg, com.zhicai.byteera.service.serversdk.ServerPush.PushMsg.Builder, com.zhicai.byteera.service.serversdk.ServerPush.PushMsgOrBuilder>(
                  msg_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:zhicaiproto.ServerPushMsg)
    }

    static {
      defaultInstance = new ServerPushMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:zhicaiproto.ServerPushMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhicaiproto_TestPayload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zhicaiproto_TestPayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhicaiproto_AddFriendRequestPayload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zhicaiproto_AddFriendRequestPayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhicaiproto_PushMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zhicaiproto_PushMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhicaiproto_ServerPushMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zhicaiproto_ServerPushMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020serverpush.proto\022\013zhicaiproto\"\033\n\013TestP" +
      "ayload\022\014\n\004data\030\001 \002(\014\"S\n\027AddFriendRequest" +
      "Payload\022\017\n\007user_id\030\001 \002(\t\022\020\n\010nickname\030\002 \002" +
      "(\t\022\025\n\rhead_portrait\030\003 \002(\t\"d\n\007PushMsg\022\'\n\004" +
      "type\030\001 \002(\0162\031.zhicaiproto.PushMsg.Type\022\017\n" +
      "\007payload\030\002 \002(\014\"\037\n\004Type\022\010\n\004Test\020\001\022\r\n\tAddF" +
      "riend\020\002\"2\n\rServerPushMsg\022!\n\003msg\030\001 \003(\0132\024." +
      "zhicaiproto.PushMsgB2\n$com.zhicai.byteer" +
      "a.service.serversdkB\nServerPush"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_zhicaiproto_TestPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zhicaiproto_TestPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zhicaiproto_TestPayload_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_zhicaiproto_AddFriendRequestPayload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zhicaiproto_AddFriendRequestPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zhicaiproto_AddFriendRequestPayload_descriptor,
        new java.lang.String[] { "UserId", "Nickname", "HeadPortrait", });
    internal_static_zhicaiproto_PushMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_zhicaiproto_PushMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zhicaiproto_PushMsg_descriptor,
        new java.lang.String[] { "Type", "Payload", });
    internal_static_zhicaiproto_ServerPushMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_zhicaiproto_ServerPushMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zhicaiproto_ServerPushMsg_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
